# Dependencies
encoding:         'utf-8'
markdown:         kramdown
pygments:         true

title:            Cedric
description:      因为兴趣, 所以coding!
url:              chenzhong.cc
baseur:           http://chenzhong.cc
signoff:          Cedric # Your name.
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
google_analytics_id: # set tracking, UA-XXXX-Y.

links:
  - name:         关于我
    url:          /about
  - name:         Feed
    url:          /feed.xml
  - name:         博客
    url:          http://chenzhong.cc
    external:     true
  - name:         邮箱
    url:          mailto:cedric_chenzhong@163.com
    external:     true
  - name:         GitHub
    url:          http://github.com/chenzhong/
    external:     true

pygments:         true
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:     [autolink, tables]
